
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const FETCH_MOVIES = 'FETCH_MOVIES'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
export const MOVIE_DETAILS = 'MOVIE_DETAILS'
export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const IS_LOGGED_OUT = 'IS_LOGGED_OUT'